peer:
    fileSystemPath: $HOME/hyperledgerRocksDB/1
    db:
        maxLogFileSize: 10485760
        keepLogFileNum: 10
        logLevel: "warn"

    profile:
        enabled:     false
        listenAddress: 0.0.0.0:6060
