FROM ubuntu:bionic
WORKDIR /root
COPY geth /usr/bin/geth
COPY 10.json core.yaml config.yaml /root/
RUN apt update && apt install -y --reinstall ca-certificates \
    && echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list \
    && apt update -q && apt install --yes --no-install-recommends build-essential flex bison wget subversion m4 python3 python3-dev python3-setuptools libgmp-dev libssl-dev git curl \
    && curl -SL https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz | tar xzC ./ && cd pbc-0.5.14 && ./configure LDFLAGS="-lgmp" && make && make install \
    && cd .. && rm pbc-0.5.14 -rf && git clone https://github.com/facebook/rocksdb.git && cd rocksdb && git checkout 4.1.fb && make shared_lib \
    && rm .git -rf \
    && ln -sf /root/rocksdb/librocksdb.so.4.1.0 /usr/local/lib/librocksdb.so \
    && ln -sf /root/rocksdb/librocksdb.so.4.1.0 /usr/local/lib/librocksdb.so.4 \
    && ln -sf /root/rocksdb/librocksdb.so.4.1.0 /usr/local/lib/librocksdb.so.4.1 \
    && ln -sf /root/rocksdb/librocksdb.so.4.1.0 /usr/local/lib/librocksdb.so.4.1.0 \
    && cp include/rocksdb /usr/include/ -r && ldconfig \
    && rm /var/cache/apt/archives/* -rf \
    && apt purge git -y \
    && apt autoremove -y \
    && mkdir /root/.geth-pbft && mv /root/config.yaml /root/.geth-pbft \
    && /usr/bin/geth --datadir /root/abc init /root/10.json
EXPOSE 8545 30303
ENTRYPOINT [ "geth" ]
